#!/usr/bin/env bash
# ControlPlane AI — Structural Integrity Validator
# Zero dependencies. Run from repo root: ./scripts/validate.sh

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
RESET='\033[0m'

PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0

pass() { ((PASS_COUNT++)); printf "${GREEN}  PASS${RESET}  %s\n" "$1"; }
fail() { ((FAIL_COUNT++)); printf "${RED}  FAIL${RESET}  %s\n" "$1"; }
warn() { ((WARN_COUNT++)); printf "${YELLOW}  WARN${RESET}  %s\n" "$1"; }

header() { printf "\n${BOLD}── %s ──${RESET}\n" "$1"; }

# ── Ensure we're at repo root ──────────────────────────────────────────────
if [[ ! -f "AGENTS.md" || ! -d ".agent" ]]; then
  printf "${RED}Error: Run this script from the repo root.${RESET}\n"
  exit 1
fi

# ═══════════════════════════════════════════════════════════════════════════
# 1. Index Completeness
# ═══════════════════════════════════════════════════════════════════════════
header "1. Index Completeness"

# Extract paths from markdown table rows in control-plane-index.md
# Matches backtick-wrapped paths like `path/to/file`
while IFS= read -r path; do
  if [[ "$path" == ".agent/repo-specific-index.md" ]]; then
    if [[ -f "$path" ]]; then
      pass "Index path exists: $path"
    else
      warn "Expected-missing (auto-generated by bootstrap): $path"
    fi
  elif [[ -d "$path" ]]; then
    pass "Index path exists: $path (directory)"
  elif [[ -f "$path" ]]; then
    pass "Index path exists: $path"
  else
    fail "Index path missing: $path"
  fi
done < <(grep -oE '`\.[^`]+`' .agent/control-plane-index.md | tr -d '`' | sort -u)

# ═══════════════════════════════════════════════════════════════════════════
# 2. Skill Meta-Template Conformance
# ═══════════════════════════════════════════════════════════════════════════
header "2. Skill Meta-Template Conformance"

for skill in .agent/skills/*.md; do
  name="$(basename "$skill")"
  for section in "Purpose" "Rules" "Examples"; do
    if grep -q "^## $section" "$skill"; then
      pass "$name has ## $section"
    else
      if [[ "$name" == "git.md" ]]; then
        warn "$name missing ## $section (known non-compliant structure)"
      else
        fail "$name missing ## $section"
      fi
    fi
  done
done

# ═══════════════════════════════════════════════════════════════════════════
# 3. Plan Frontmatter
# ═══════════════════════════════════════════════════════════════════════════
header "3. Plan Frontmatter"

REQUIRED_PLAN_FIELDS=("title" "status" "tier" "created" "updated")
VALID_PLAN_STATUSES="draft|approved|executing|completed"
VALID_PLAN_TIERS="Small|Medium|Large"

for plan in .agent/plans/*.md; do
  [[ "$(basename "$plan")" == ".gitkeep" ]] && continue
  name="$(basename "$plan")"

  # Check that file starts with ---
  if ! head -1 "$plan" | grep -q '^---$'; then
    fail "$name: no YAML frontmatter"
    continue
  fi

  # Extract frontmatter (between first and second ---)
  frontmatter="$(sed -n '1,/^---$/{ /^---$/d; p; }' "$plan" | sed '1d')"
  # Actually need the content between first --- and second ---
  frontmatter="$(awk '/^---$/{n++; next} n==1' "$plan")"

  for field in "${REQUIRED_PLAN_FIELDS[@]}"; do
    if echo "$frontmatter" | grep -q "^${field}:"; then
      pass "$name has '$field'"
    else
      fail "$name missing '$field'"
    fi
  done

  # Validate status value
  status_val="$(echo "$frontmatter" | grep '^status:' | head -1 | sed 's/^status:[[:space:]]*//')"
  if [[ -n "$status_val" ]]; then
    if echo "$status_val" | grep -qE "^(${VALID_PLAN_STATUSES})$"; then
      pass "$name status='$status_val' is valid"
    else
      fail "$name status='$status_val' not in {${VALID_PLAN_STATUSES}}"
    fi
  fi

  # Validate tier value
  tier_val="$(echo "$frontmatter" | grep '^tier:' | head -1 | sed 's/^tier:[[:space:]]*//')"
  if [[ -n "$tier_val" ]]; then
    if echo "$tier_val" | grep -qE "^(${VALID_PLAN_TIERS})$"; then
      pass "$name tier='$tier_val' is valid"
    else
      fail "$name tier='$tier_val' not in {${VALID_PLAN_TIERS}}"
    fi
  fi
done

# ═══════════════════════════════════════════════════════════════════════════
# 4. Brief Frontmatter
# ═══════════════════════════════════════════════════════════════════════════
header "4. Brief Frontmatter"

REQUIRED_BRIEF_FIELDS=("title" "status" "created" "last_validated")
VALID_BRIEF_STATUSES="active|completed|archived"

brief_count=0
for brief in .agent/briefs/*.md; do
  [[ "$(basename "$brief")" == ".gitkeep" ]] && continue
  [[ ! -f "$brief" ]] && continue
  brief_count=$((brief_count + 1))
  name="$(basename "$brief")"

  if ! head -1 "$brief" | grep -q '^---$'; then
    fail "$name: no YAML frontmatter"
    continue
  fi

  frontmatter="$(awk '/^---$/{n++; next} n==1' "$brief")"

  for field in "${REQUIRED_BRIEF_FIELDS[@]}"; do
    if echo "$frontmatter" | grep -q "^${field}:"; then
      pass "$name has '$field'"
    else
      fail "$name missing '$field'"
    fi
  done

  # Validate status value
  status_val="$(echo "$frontmatter" | grep '^status:' | head -1 | sed 's/^status:[[:space:]]*//')"
  if [[ -n "$status_val" ]]; then
    if echo "$status_val" | grep -qE "^(${VALID_BRIEF_STATUSES})$"; then
      pass "$name status='$status_val' is valid"
    else
      fail "$name status='$status_val' not in {${VALID_BRIEF_STATUSES}}"
    fi
  fi
done

if [[ $brief_count -eq 0 ]]; then
  pass "No briefs to validate (directory empty — expected)"
fi

# ═══════════════════════════════════════════════════════════════════════════
# 5. Cross-Reference Integrity
# ═══════════════════════════════════════════════════════════════════════════
header "5. Cross-Reference Integrity"

for md_file in $(find .agent -name '*.md' -type f); do
  dir="$(dirname "$md_file")"

  # Strip fenced code blocks before extracting links
  content="$(awk '/^```/{skip=!skip; next} !skip{print}' "$md_file")"

  # Extract markdown links: [text](path)
  while IFS= read -r link; do
    [[ -z "$link" ]] && continue
    # Skip URLs (http/https/mailto)
    [[ "$link" =~ ^https?:// || "$link" =~ ^mailto: ]] && continue
    # Skip fragment-only links
    [[ "$link" =~ ^# ]] && continue
    # Strip fragment from path
    link_path="${link%%#*}"
    [[ -z "$link_path" ]] && continue

    # Known placeholder in skill template
    if [[ "$link_path" == "relative/path" ]]; then
      warn "Placeholder link [Related Skill](relative/path) in $(basename "$md_file")"
      continue
    fi

    # Resolve relative to the file's directory
    if [[ "$link_path" == /* ]]; then
      resolved="$link_path"
    elif [[ "$link_path" == ./* ]]; then
      resolved="$dir/${link_path#./}"
    else
      resolved="$dir/$link_path"
    fi

    if [[ -f "$resolved" || -d "$resolved" ]]; then
      pass "Link OK: $(basename "$md_file") → $link_path"
    else
      fail "Broken link: $(basename "$md_file") → $link_path (resolved: $resolved)"
    fi
  done < <(echo "$content" | grep -oE '\[[^]]*\]\([^)]+\)' | grep -oE '\([^)]+\)' | tr -d '()')
done

# ═══════════════════════════════════════════════════════════════════════════
# 6. Entry Point References
# ═══════════════════════════════════════════════════════════════════════════
header "6. Entry Point References"

ENTRY_POINTS=(
  "AGENTS.md"
  "CLAUDE.md"
  ".cursor/rules/controlplane.mdc"
  ".github/copilot-instructions.md"
)

for ep in "${ENTRY_POINTS[@]}"; do
  if [[ ! -f "$ep" ]]; then
    fail "Entry point missing: $ep"
    continue
  fi

  if grep -q "control-plane-index.md" "$ep"; then
    pass "$ep references control-plane-index.md"
  else
    fail "$ep does not reference control-plane-index.md"
  fi
done

# ═══════════════════════════════════════════════════════════════════════════
# 7. No Stale References
# ═══════════════════════════════════════════════════════════════════════════
header "7. No Stale References"

stale_found=false
while IFS= read -r match; do
  file="$(echo "$match" | cut -d: -f1)"
  # Normalize path (strip leading ./)
  file="${file#./}"
  # Plan files get a warning (historical documentation)
  if [[ "$file" == .agent/plans/* ]]; then
    warn "Stale .agent/index.md reference in plan file: $file (historical)"
  else
    fail "Stale .agent/index.md reference: $file"
    stale_found=true
  fi
done < <(grep -rn '\.agent/index\.md' --include='*.md' --include='*.mdc' . 2>/dev/null || true)

if [[ "$stale_found" == false ]]; then
  # Check if there were any matches at all (all were in plans)
  stale_total="$(grep -rl '\.agent/index\.md' --include='*.md' --include='*.mdc' . 2>/dev/null | wc -l | tr -d ' ')"
  if [[ "$stale_total" -eq 0 ]]; then
    pass "No stale .agent/index.md references found"
  else
    pass "All .agent/index.md references are in plan files (historical only)"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════════════
printf "\n${BOLD}── Summary ──${RESET}\n"
printf "${GREEN}  %d passed${RESET}  ${RED}%d failed${RESET}  ${YELLOW}%d warnings${RESET}\n" \
  "$PASS_COUNT" "$FAIL_COUNT" "$WARN_COUNT"

if [[ "$FAIL_COUNT" -gt 0 ]]; then
  exit 1
else
  exit 0
fi
